<title>Guard Dog GPS Tracking &amp; Security<?php if($title) echo " - $title"; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="alexaVerifyID" content="nX6lOqfE4YUm99YzB7mhgvC5_gA" />
<meta name="robots" content="INDEX,FOLLOW" />
<meta name="Description" content="Guard Dog GPS manufactures AutoTrac, FleetTrac, MotoTrac and MarineTrac. Tracking and Security Systems for Cars, Fleets, Motorcycles and Watercraft." />
<meta name="keywords" content="guarddoggps, guard dog, AutoTrac, car gps, MotoTrac, motorcycle gps, FleetTrac, truck management, MarineTrac, boat gps, tracking security, gps products, security devices, speed control, virtual fence, speed alerts, gps devices, smart tracker, small gps, personal gps, gps spy" />
<meta name="copyright" content="Copyright (c) 2011 - GuardDogGPS Inc." />
<meta name="author" content="GuardDogGPS Admin" />
<meta name="viewport" content="width=1060" />

<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
<link href="css/style.css" rel="stylesheet" type="text/css" />
<link href="css/top-bar.css" rel="stylesheet" type="text/css" />

<!--[if lt IE 9]>
  <script type="text/javascript" src="http://info.template-help.com/files/ie6_warning/ie6_script_other.js"></script>
  <script type="text/javascript" src="js/html5.js"></script>
<![endif]-->

<?php include("include/google-analytics.inc"); ?>
